package top.devoty.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import top.devoty.domain.Blog;
import top.devoty.domain.BlogExample;

/**
* Created by Mybatis Generator on 2020/06/28
*/
public interface BlogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_blog
     *
     * @mbg.generated Sun Jun 28 12:42:11 CST 2020
     */
    long countByExample(BlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_blog
     *
     * @mbg.generated Sun Jun 28 12:42:11 CST 2020
     */
    int deleteByExample(BlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_blog
     *
     * @mbg.generated Sun Jun 28 12:42:11 CST 2020
     */
    int deleteByPrimaryKey(Long blogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_blog
     *
     * @mbg.generated Sun Jun 28 12:42:11 CST 2020
     */
    int insert(Blog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_blog
     *
     * @mbg.generated Sun Jun 28 12:42:11 CST 2020
     */
    int insertSelective(Blog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_blog
     *
     * @mbg.generated Sun Jun 28 12:42:11 CST 2020
     */
    List<Blog> selectByExample(BlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_blog
     *
     * @mbg.generated Sun Jun 28 12:42:11 CST 2020
     */
    Blog selectByPrimaryKey(Long blogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_blog
     *
     * @mbg.generated Sun Jun 28 12:42:11 CST 2020
     */
    int updateByExampleSelective(@Param("record") Blog record, @Param("example") BlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_blog
     *
     * @mbg.generated Sun Jun 28 12:42:11 CST 2020
     */
    int updateByExample(@Param("record") Blog record, @Param("example") BlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_blog
     *
     * @mbg.generated Sun Jun 28 12:42:11 CST 2020
     */
    int updateByPrimaryKeySelective(Blog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_blog
     *
     * @mbg.generated Sun Jun 28 12:42:11 CST 2020
     */
    int updateByPrimaryKey(Blog record);
}