package top.devoty.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import top.devoty.domain.Link;
import top.devoty.domain.LinkExample;

/**
* Created by Mybatis Generator on 2020/06/28
*/
public interface LinkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_link
     *
     * @mbg.generated Sun Jun 28 12:42:11 CST 2020
     */
    long countByExample(LinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_link
     *
     * @mbg.generated Sun Jun 28 12:42:11 CST 2020
     */
    int deleteByExample(LinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_link
     *
     * @mbg.generated Sun Jun 28 12:42:11 CST 2020
     */
    int deleteByPrimaryKey(Integer linkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_link
     *
     * @mbg.generated Sun Jun 28 12:42:11 CST 2020
     */
    int insert(Link record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_link
     *
     * @mbg.generated Sun Jun 28 12:42:11 CST 2020
     */
    int insertSelective(Link record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_link
     *
     * @mbg.generated Sun Jun 28 12:42:11 CST 2020
     */
    List<Link> selectByExample(LinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_link
     *
     * @mbg.generated Sun Jun 28 12:42:11 CST 2020
     */
    Link selectByPrimaryKey(Integer linkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_link
     *
     * @mbg.generated Sun Jun 28 12:42:11 CST 2020
     */
    int updateByExampleSelective(@Param("record") Link record, @Param("example") LinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_link
     *
     * @mbg.generated Sun Jun 28 12:42:11 CST 2020
     */
    int updateByExample(@Param("record") Link record, @Param("example") LinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_link
     *
     * @mbg.generated Sun Jun 28 12:42:11 CST 2020
     */
    int updateByPrimaryKeySelective(Link record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_link
     *
     * @mbg.generated Sun Jun 28 12:42:11 CST 2020
     */
    int updateByPrimaryKey(Link record);
}