package top.devoty.domain;

import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
* Created by Mybatis Generator on 2020/06/28
*/
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Blog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_blog.blog_id
     *
     * @mbg.generated Sun Jun 28 12:42:11 CST 2020
     */
    private Long blogId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_blog.blog_title
     *
     * @mbg.generated Sun Jun 28 12:42:11 CST 2020
     */
    private String blogTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_blog.content_id
     *
     * @mbg.generated Sun Jun 28 12:42:11 CST 2020
     */
    private String contentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_blog.blog_sub_url
     *
     * @mbg.generated Sun Jun 28 12:42:11 CST 2020
     */
    private String blogSubUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_blog.md_hash
     *
     * @mbg.generated Sun Jun 28 12:42:11 CST 2020
     */
    private String mdHash;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_blog.blog_cover_image
     *
     * @mbg.generated Sun Jun 28 12:42:11 CST 2020
     */
    private String blogCoverImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_blog.blog_category_id
     *
     * @mbg.generated Sun Jun 28 12:42:11 CST 2020
     */
    private Integer blogCategoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_blog.blog_tags
     *
     * @mbg.generated Sun Jun 28 12:42:11 CST 2020
     */
    private String blogTags;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_blog.blog_status
     *
     * @mbg.generated Sun Jun 28 12:42:11 CST 2020
     */
    private Integer blogStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_blog.blog_views
     *
     * @mbg.generated Sun Jun 28 12:42:11 CST 2020
     */
    private Long blogViews;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_blog.enable_comment
     *
     * @mbg.generated Sun Jun 28 12:42:11 CST 2020
     */
    private Integer enableComment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_blog.is_deleted
     *
     * @mbg.generated Sun Jun 28 12:42:11 CST 2020
     */
    private Integer isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_blog.status_cd
     *
     * @mbg.generated Sun Jun 28 12:42:11 CST 2020
     */
    private Integer statusCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_blog.status_time
     *
     * @mbg.generated Sun Jun 28 12:42:11 CST 2020
     */
    private Date statusTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_blog.create_staff
     *
     * @mbg.generated Sun Jun 28 12:42:11 CST 2020
     */
    private String createStaff;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_blog.create_time
     *
     * @mbg.generated Sun Jun 28 12:42:11 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_blog.update_staff
     *
     * @mbg.generated Sun Jun 28 12:42:11 CST 2020
     */
    private String updateStaff;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_blog.update_time
     *
     * @mbg.generated Sun Jun 28 12:42:11 CST 2020
     */
    private Date updateTime;
}