package top.devoty.domain;

import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
* Created by Mybatis Generator on 2020/06/28
*/
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Config {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_config.id
     *
     * @mbg.generated Sun Jun 28 12:42:11 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_config.config_name
     *
     * @mbg.generated Sun Jun 28 12:42:11 CST 2020
     */
    private String configName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_config.config_value
     *
     * @mbg.generated Sun Jun 28 12:42:11 CST 2020
     */
    private String configValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_config.status_cd
     *
     * @mbg.generated Sun Jun 28 12:42:11 CST 2020
     */
    private String statusCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_config.status_time
     *
     * @mbg.generated Sun Jun 28 12:42:11 CST 2020
     */
    private Date statusTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_config.create_staff
     *
     * @mbg.generated Sun Jun 28 12:42:11 CST 2020
     */
    private String createStaff;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_config.create_time
     *
     * @mbg.generated Sun Jun 28 12:42:11 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_config.update_staff
     *
     * @mbg.generated Sun Jun 28 12:42:11 CST 2020
     */
    private String updateStaff;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_config.update_time
     *
     * @mbg.generated Sun Jun 28 12:42:11 CST 2020
     */
    private Date updateTime;
}