package top.devoty.domain;

import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
* Created by Mybatis Generator on 2020/06/29
*/
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Link {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_link.link_id
     *
     * @mbg.generated Mon Jun 29 11:23:50 CST 2020
     */
    private Integer linkId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_link.link_type
     *
     * @mbg.generated Mon Jun 29 11:23:50 CST 2020
     */
    private Integer linkType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_link.link_name
     *
     * @mbg.generated Mon Jun 29 11:23:50 CST 2020
     */
    private String linkName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_link.link_url
     *
     * @mbg.generated Mon Jun 29 11:23:50 CST 2020
     */
    private String linkUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_link.link_description
     *
     * @mbg.generated Mon Jun 29 11:23:50 CST 2020
     */
    private String linkDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_link.link_rank
     *
     * @mbg.generated Mon Jun 29 11:23:50 CST 2020
     */
    private Integer linkRank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_link.is_deleted
     *
     * @mbg.generated Mon Jun 29 11:23:50 CST 2020
     */
    private Integer isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_link.create_time
     *
     * @mbg.generated Mon Jun 29 11:23:50 CST 2020
     */
    private Date createTime;
}